version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.Spark
    versions:
    - 1.1.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
