name: deploy nuget

on:
    create:
        tags:
            - v*

jobs:
    publish-nuget:
        runs-on: ubuntu-latest
        env:
            nuget_api_key: ${{ secrets.NUGET_API_KEY }}
            DOTNET_WORKER_DIR: /usr/local/bin/
            SPARK_RUNNER_DIR: /home/runner/bin/
        steps:
            -   uses: actions/checkout@v1

            -   name: Setup .NET Core
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: 3.1.100

            -   name: Build
                run: dotnet build --configuration Release
                working-directory: ./src/deequ

            -   name: Scripts permissions
                run: chmod +x deploy/install-worker.sh && chmod +x deploy/download-spark.sh

            -   name: Download OpenJDK
                uses: sormuras/download-jdk@v1
                with:
                    feature: 8

            -   name: Install Apache Spark
                run: deploy/download-spark.sh /home/runner/bin/

            -   name: Install .NET Worker
                run: deploy/install-worker.sh github https://github.com/dotnet/spark/releases/download/v0.12.1/Microsoft.Spark.Worker.netcoreapp3.1.linux-x64-0.12.1.tar.gz /usr/local/bin/

            -   name: Run unit tests
                run: dotnet test --configuration Release
                working-directory: ./tests/deequ.tests

            -   name: Generate nuget package
                run: dotnet pack --configuration Release -o nupkg
                working-directory: ./src/deequ

            -   name: Publish nuget package
                run: dotnet tool install --global GitReleaseManager.Tool
                    tag="${GITHUB_REF:10}"
                    owner="${GITHUB_REPOSITORY%/*}"
                    repo="${GITHUB_REPOSITORY#*/}"
                    dotnet-gitreleasemanager create -m ${tag} --token ${{secrets.GITHUB_TOKEN}} -o ${owner} -r ${repo}
                    dotnet-gitreleasemanager close -m ${tag} --token ${{secrets.GITHUB_TOKEN}} -o ${owner} -r ${repo}
                    dotnet-gitreleasemanager publish -t ${tag} --token ${{secrets.GITHUB_TOKEN}} -o ${owner} -r ${repo}
